import { Resend } from 'resend';
import { GeneratedRecipe } from './gemini';

// Initialize Resend with the API key
const resend = new Resend(process.env.RESEND_API_KEY);

interface RecipeEmailData {
  recipe: Partial<GeneratedRecipe>;
  recipientEmail: string;
}

/**
 * Send a recipe via email using Resend
 */
export async function sendRecipeEmail({ recipe, recipientEmail }: RecipeEmailData): Promise<boolean> {
  if (!process.env.RESEND_API_KEY) {
    console.error('Missing RESEND_API_KEY environment variable.');
    return false;
  }

  if (!recipe || !recipe.title) {
    console.error('Cannot send email: Recipe data is incomplete');
    return false;
  }

  try {
    // Create HTML content for the email
    const htmlContent = `
      <div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto;">
        <h1 style="color: #4a5568;">${recipe.title}</h1>

        ${recipe.description ? `<p style="color: #4a5568; margin-bottom: 20px;">${recipe.description}</p>` : ''}

        <div style="margin-bottom: 20px;">
          <h2 style="color: #2d3748;">Ingredients</h2>
          <div style="white-space: pre-line; color: #4a5568;">
            ${recipe.ingredients ? recipe.ingredients : 'Ingredients not available'}
          </div>
        </div>

        <div style="margin-bottom: 20px;">
          <h2 style="color: #2d3748;">Instructions</h2>
          <div style="white-space: pre-line; color: #4a5568;">
            ${recipe.instructions ? recipe.instructions : 'Instructions not available'}
          </div>
        </div>

        <div style="margin-top: 30px; font-size: 14px; color: #718096;">
          <p>Meal Type: ${recipe.mealType || 'N/A'}</p>
          <p>Prep Time: ${recipe.prepTime ? `${recipe.prepTime} minutes` : 'N/A'}</p>
          <p>Servings: ${recipe.servings || 'N/A'}</p>
        </div>

        <p style="margin-top: 30px; font-size: 12px; color: #a0aec0;">
          This recipe was generated by Chef Pierre's AI Recipe Generator. Enjoy your cooking!
        </p>
      </div>
    `;

    console.log('Attempting to send email via Resend to:', recipientEmail);
    // Send email using Resend
    const { data, error } = await resend.emails.send({
      from: 'Chef Pierre <noreply@resend.dev>',
      to: [recipientEmail],
      subject: `Recipe: ${recipe.title}`,
      html: htmlContent,
      text: `${recipe.title}\n\n${recipe.description || ''}\n\nIngredients:\n${recipe.ingredients || 'Not available'}\n\nInstructions:\n${recipe.instructions || 'Not available'}\n\nMeal Type: ${recipe.mealType || 'N/A'}\nPrep Time: ${recipe.prepTime ? `${recipe.prepTime} minutes` : 'N/A'}\nServings: ${recipe.servings || 'N/A'}\n\nThis recipe was generated by Chef Pierre's AI Recipe Generator. Enjoy your cooking!`,
    });

    if (error) {
      console.error('Error sending email with Resend:', error);
      return false;
    }

    console.log('Email sent successfully with Resend:', data?.id);
    return true;
  } catch (error) {
    console.error('Error sending email:', error);
    return false;
  }
}

/**
 * Send a test email to verify configuration
 */
export async function sendTestEmail(recipientEmail: string): Promise<boolean> {
  if (!process.env.RESEND_API_KEY) {
    console.error('Missing RESEND_API_KEY environment variable.');
    return false;
  }

  try {
    console.log('Attempting to send test email via Resend to:', recipientEmail);
    // Send email using Resend
    const { data, error } = await resend.emails.send({
      from: 'CuisineMuse <no-reply@resend.dev>',
      to: [recipientEmail],
      subject: 'Welcome to CuisineMuse 🍳 Your AI-Powered Kitchen Companion',
      html: `
        <div style="font-family: sans-serif; line-height: 1.6; color: #333; max-width: 600px; margin: auto;">
          <h1 style="color: #ff6f61;">Welcome to CuisineMuse</h1>
          <p>We're so glad you're here.</p>

          <p><strong>CuisineMuse</strong> brings the magic of AI to your kitchen, helping you create delicious meals with less stress and more creativity. Whether you're working with a few ingredients or planning something special, we're here to inspire you.</p>

          <hr style="border: none; border-top: 1px solid #eee;" />

          <h2 style="color: #ff6f61;">Here's what you can explore:</h2>
          <ul>
            <li>🍝 Personalized recipes based on your ingredients and preferences</li>
            <li>⏱️ Quick meals tailored to your schedule</li>
            <li>🌍 Global flavors made simple and approachable</li>
          </ul>

          <p>Try out your first AI-powered recipe and see what's cooking. Your next favorite dish could be just a few clicks away.</p>

          <p style="margin-top: 2em;">Happy cooking,<br /><strong>The CuisineMuse Team</strong></p>

          <hr style="border: none; border-top: 1px solid #eee;" />
          <p style="font-size: 0.8em; color: #888;">This message was automatically generated by CuisineMuse.</p>
        </div>
      `,
      text: 'Welcome to CuisineMuse! We\'re so glad you\'re here. CuisineMuse brings the magic of AI to your kitchen, helping you create delicious meals with less stress and more creativity. Try out your first AI-powered recipe and see what\'s cooking. Your next favorite dish could be just a few clicks away. Happy cooking, The CuisineMuse Team',
    });

    if (error) {
      console.error('Error sending test email with Resend:', error);
      return false;
    }

    console.log('Test email sent successfully with Resend:', data?.id);
    return true;
  } catch (error) {
    console.error('Error sending test email:', error);
    return false;
  }
}